---
packages:
    - vim
    - zsh
    - tmux
    - git
    - mosh
    - tlp
    - powertop
    - cowsay
packages_ubuntu:
    - python-pip
    - silversearcher-ag
packages_fedora:
    - the_silver_searcher
