---
- name: install standard set of applications
  apt: name={{ item }} state=latest
  become: true
  with_items:
      - vim
      - zsh
      - tmux
      - git
      - mosh
      - tlp
      - powertop
      - python-pip
