# Fedora only # dnf install -y ansible python2 python2-dnf libselinux-python
# # ansible-playbook laptop.yml -c local -K
---

- name: Set up sakjur's laptop
  hosts: localhost
  remote_user: sakjur
  become_user: root 

  roles:
      - laptop

  tasks:
      - name: set default shell to zsh
        user: name=sakjur shell=/usr/bin/zsh
        become: true

      - name: create projects directory
        file: path=~/projects state=directory

